// src/components/calendar/mockData.ts
// Figma export에서 확인된 실제 이벤트 데이터 기반
import type { CalendarEvent } from './types';

const y = new Date().getFullYear();
const m = new Date().getMonth();
const d = new Date().getDate();

// 피그마 export에서 확인된 이벤트들 (4월 기준)
export const MOCK_EVENTS: CalendarEvent[] = [
  // === 오늘 기준 이벤트 ===
  {
    eventId: 'today-1',
    source: 'GOOGLE',
    title: '김철수 대표 미팅',
    startAt: new Date(y, m, d, 9, 0).toISOString(),
    endAt: new Date(y, m, d, 10, 30).toISOString(),
    category: '미팅',
    accountName: '삼성SDS',
    accountId: 1,
    pipelineStage: { stageId: 4, stageName: '제안 발표', stageCode: 'PROPOSAL_PRESENT' },
    memo: '고객 측에서 예산 확인 후 Q3 착수 희망. 경쟁사 대비 가격 강조 필요.',
    attendees: { internal: ['홍길동'], external: ['김철수'] },
  },
  {
    eventId: 'today-2',
    source: 'FINT',
    title: '제안서 발송',
    startAt: new Date(y, m, d, 11, 0).toISOString(),
    endAt: new Date(y, m, d, 11, 20).toISOString(),
    category: '이메일',
    accountName: 'LG CNS',
    accountId: 2,
    pipelineStage: { stageId: 3, stageName: '제안서 작성', stageCode: 'PROPOSAL_WRITING' },
  },
  {
    eventId: 'today-3',
    source: 'FINT',
    title: '이영희 팀장 전화',
    startAt: new Date(y, m, d, 13, 0).toISOString(),
    endAt: new Date(y, m, d, 13, 30).toISOString(),
    category: '전화',
    accountName: 'Toss Bank',
    accountId: 3,
    pipelineStage: { stageId: 2, stageName: '니즈 파악', stageCode: 'NEEDS_ANALYSIS' },
  },
  {
    eventId: 'today-4',
    source: 'FINT',
    title: '주간 보고 작성',
    startAt: new Date(y, m, d, 17, 0).toISOString(),
    endAt: new Date(y, m, d, 18, 0).toISOString(),
    category: '업무',
  },

  // === 피그마 export 날짜별 이벤트 ===
  {
    eventId: 'ev-10',
    source: 'FINT',
    title: 'Q1 마감 리포트',
    startAt: new Date(y, m, d + 3, 10, 0).toISOString(),
    endAt: new Date(y, m, d + 3, 11, 0).toISOString(),
    category: '업무',
  },
  {
    eventId: 'ev-14',
    source: 'GOOGLE',
    title: 'Hyundai Card 기술검토',
    startAt: new Date(y, m, d + 7, 15, 0).toISOString(),
    endAt: new Date(y, m, d + 7, 17, 0).toISOString(),
    category: '미팅',
    accountName: 'Hyundai Card',
    accountId: 4,
    pipelineStage: { stageId: 5, stageName: '협상 중', stageCode: 'NEGOTIATION' },
  },
  {
    eventId: 'ev-15',
    source: 'GOOGLE',
    title: 'Toss Bank 분기 리뷰',
    startAt: new Date(y, m, d + 8, 14, 0).toISOString(),
    endAt: new Date(y, m, d + 8, 15, 30).toISOString(),
    category: '미팅',
    accountName: 'Toss Bank',
    accountId: 3,
    pipelineStage: { stageId: 2, stageName: '니즈 파악', stageCode: 'NEEDS_ANALYSIS' },
  },
  {
    eventId: 'ev-16',
    source: 'GOOGLE',
    title: 'Coupang API 미팅',
    startAt: new Date(y, m, d + 9, 11, 0).toISOString(),
    endAt: new Date(y, m, d + 9, 12, 0).toISOString(),
    category: '미팅',
    accountName: 'Coupang',
    accountId: 5,
    pipelineStage: { stageId: 1, stageName: '첫 미팅 준비', stageCode: 'FIRST_MEETING' },
  },
  {
    eventId: 'ev-17',
    source: 'FINT',
    title: 'Samsung SDS 팔로업',
    startAt: new Date(y, m, d + 10, 10, 0).toISOString(),
    endAt: new Date(y, m, d + 10, 10, 30).toISOString(),
    category: '전화',
    accountName: 'Samsung SDS',
    accountId: 6,
    pipelineStage: { stageId: 2, stageName: '니즈 파악', stageCode: 'NEEDS_ANALYSIS' },
  },
  {
    eventId: 'ev-19',
    source: 'FINT',
    title: '↪ Q2 세일즈 캠페인',
    startAt: new Date(y, m, d + 12, 10, 0).toISOString(),
    endAt: new Date(y, m, d + 12, 11, 0).toISOString(),
    category: '업무',
  },
  {
    eventId: 'ev-20',
    source: 'FINT',
    title: 'LG CNS 사전 콜',
    startAt: new Date(y, m, d + 13, 11, 0).toISOString(),
    endAt: new Date(y, m, d + 13, 12, 0).toISOString(),
    category: '전화',
    accountName: 'LG CNS',
    accountId: 2,
    pipelineStage: { stageId: 3, stageName: '제안서 작성', stageCode: 'PROPOSAL_WRITING' },
  },
  {
    eventId: 'ev-21',
    source: 'FINT',
    title: '신임 CFO ROI 리포트',
    startAt: new Date(y, m, d + 14, 17, 0).toISOString(),
    endAt: new Date(y, m, d + 14, 18, 0).toISOString(),
    category: '이메일',
    accountName: 'Naver Cloud',
    accountId: 7,
    pipelineStage: { stageId: 2, stageName: '니즈 파악', stageCode: 'NEEDS_ANALYSIS' },
  },
  {
    eventId: 'ev-22a',
    source: 'FINT',
    title: '주간 영업팀 스탠드업',
    startAt: new Date(y, m, d + 15, 9, 0).toISOString(),
    endAt: new Date(y, m, d + 15, 9, 30).toISOString(),
    category: '업무',
    accountName: 'Hyundai Card',
    accountId: 4,
  },
  {
    eventId: 'ev-22b',
    source: 'GOOGLE',
    title: 'Kakao Mobility 견적 검토',
    startAt: new Date(y, m, d + 15, 10, 30).toISOString(),
    endAt: new Date(y, m, d + 15, 12, 0).toISOString(),
    category: '미팅',
    accountName: 'Kakao Mobility',
    accountId: 8,
    pipelineStage: { stageId: 3, stageName: '제안서 작성', stageCode: 'PROPOSAL_WRITING' },
  },
  {
    eventId: 'ev-23',
    source: 'FINT',
    title: 'Hyundai Card ROI 자료',
    startAt: new Date(y, m, d + 16, 14, 0).toISOString(),
    endAt: new Date(y, m, d + 16, 14, 30).toISOString(),
    category: '이메일',
    accountName: 'Hyundai Card',
    accountId: 4,
    pipelineStage: { stageId: 5, stageName: '협상 중', stageCode: 'NEGOTIATION' },
  },
  {
    eventId: 'ev-24',
    source: 'GOOGLE',
    title: 'Naver Cloud 계약서 검토',
    startAt: new Date(y, m, d + 17, 11, 0).toISOString(),
    endAt: new Date(y, m, d + 17, 13, 0).toISOString(),
    category: '미팅',
    accountName: 'Naver',
    accountId: 9,
    pipelineStage: { stageId: 5, stageName: '협상 중', stageCode: 'NEGOTIATION' },
  },
  {
    eventId: 'ev-25',
    source: 'FINT',
    title: 'Q2 파이프라인 리뷰',
    startAt: new Date(y, m, d + 18, 10, 0).toISOString(),
    endAt: new Date(y, m, d + 18, 11, 0).toISOString(),
    category: '업무',
  },
  {
    eventId: 'ev-26',
    source: 'FINT',
    title: '↪ Q2 세일즈 캠페인',
    startAt: new Date(y, m, d + 19, 10, 0).toISOString(),
    endAt: new Date(y, m, d + 19, 11, 0).toISOString(),
    category: '업무',
  },
  {
    eventId: 'ev-27',
    source: 'GOOGLE',
    title: 'Krafton 데모 세션',
    startAt: new Date(y, m, d + 20, 14, 0).toISOString(),
    endAt: new Date(y, m, d + 20, 16, 0).toISOString(),
    category: '미팅',
    pipelineStage: { stageId: 1, stageName: '첫 미팅 준비', stageCode: 'FIRST_MEETING' },
  },
  {
    eventId: 'ev-28',
    source: 'FINT',
    title: '가격 재협상 제안',
    startAt: new Date(y, m, d + 21, 15, 0).toISOString(),
    endAt: new Date(y, m, d + 21, 15, 30).toISOString(),
    category: '이메일',
    accountName: 'Naver Cloud',
    accountId: 7,
    pipelineStage: { stageId: 5, stageName: '협상 중', stageCode: 'NEGOTIATION' },
  },
  {
    eventId: 'ev-29',
    source: 'FINT',
    title: 'Naver Cloud 본계약',
    startAt: new Date(y, m, d + 22, 14, 0).toISOString(),
    endAt: new Date(y, m, d + 22, 15, 30).toISOString(),
    category: '업무',
    accountName: 'Naver',
    accountId: 9,
    pipelineStage: { stageId: 5, stageName: '협상 중', stageCode: 'NEGOTIATION' },
  },
  {
    eventId: 'ev-30',
    source: 'GOOGLE',
    title: 'CJ Logistics 2차 미팅',
    startAt: new Date(y, m, d + 23, 11, 0).toISOString(),
    endAt: new Date(y, m, d + 23, 13, 0).toISOString(),
    category: '미팅',
    accountName: 'CJ',
    accountId: 10,
    pipelineStage: { stageId: 2, stageName: '니즈 파악', stageCode: 'NEEDS_ANALYSIS' },
  },
  {
    eventId: 'ev-31',
    source: 'GOOGLE',
    title: 'Toss Bank POC 킥오프',
    startAt: new Date(y, m, d + 24, 10, 0).toISOString(),
    endAt: new Date(y, m, d + 24, 12, 0).toISOString(),
    category: '미팅',
    accountName: 'Toss Bank',
    accountId: 3,
    pipelineStage: { stageId: 2, stageName: '니즈 파악', stageCode: 'NEEDS_ANALYSIS' },
  },
];
